### PR TITLE
Uses web hooks

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
Hi,

This PR contains 13 commits in order to help check that everything works correctly in each of them.
This PR will only work with anki 2.1.22 or later. It uses some hooks that has just be added by Glutanimate. Their purpose is to help add-ons interact with each other, by having a dedicated system in order to add javascript code into "web" windows and avoiding monkey patching

### CODE REVIEW

**Comment by BlueGreenMagick** [comment]
Hey, first of all thanks for the extensive PR. But what are tangible benefits for this addon to use webhooks instead of monkey patching?

**Comment by Arthur-Milchior** [comment]
First benefit is following Damien Elmes recommendation: https://anki.tenderapp.com/discussions/beta-testing/1704-anki-2120-updates-to-the-hook-system
> The add-on documentation has been updated to encourage add-on authors to submit pull requests for any hooks they need, and the hope is that the bulk of add-ons can move away from monkey patching in the future.

When anki's code evolves, method sometime change parameters or even name recently. If you use a hook, you have a certain guarantee that the type signature won't change. So less risk the add-on break later.

That is something that did occur a lot recently, even if it did not have any affect your add-on. This is particularly useful to allow anki to get more efficient. Damien did tell that anki 2.0 did restrict the change he could make and that, when he dropped 2.0 it could improve things which were fixed.

But the biggest point is that when you create multiple add-ons, it's easy to have them breaking each other when you monkey patch. This is of course less of a risk with "wrap" than if you didn't use the previous method. But it still means that if another add-on needs to monkey-patch a method such as Reviewer._linkHandler, it may be possible that it simply does not call your method. 

This has been a problem  with some of my add-ons, where me and other people did change the same method while wrapping was not possible

**Comment by BlueGreenMagick** [comment]
There are still a lot of people using older anki versions, so I'll leave this open for now and maybe merge it later when something breaks or we can expect mostly everyone to be using 2.1.22+.

**Comment by Arthur-Milchior** [comment]
In case you didn't know, you can now tell ankiweb that an add on should be used on Anki up to 2.1.21 and give another add-on version for 2.1.22 and later.

**Comment by BlueGreenMagick** [comment]
You can? How?

**Comment by Arthur-Milchior** [comment]
When you edit/upload an add-on, you can add numbers:
Supports: "Anki 2.1.? to ?". If you enter the second value to be "-21" it means that the add-on won't be distributed for numbers greater than 21. If you update and then click on "edit", you can then add a second version of the add-on, by indicating that it works for anki whose version is greater than 22

**Pull request closed without merging**
